services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfile:
      image: n8nio/n8n
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin
      - key: N8N_HOST
        value: n8n-i05g.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-i05g.onrender.com
      - key: TZ
        value: Europe/Berlin
